### ISSUE TITLE
typo `raw -> row`

### ISSUE THREAD

**Issue by yuyamashiro** [Jij-Inc/ommx#117]
raw -> row

https://github.com/Jij-Inc/ommx/blob/260f6a83983bb8aade38a986e815682498431fd8/python/ommx/ommx/v1/__init__.py#L642

**Comment by Shitaro** [comment]
Thank you for reporting the bug.
This is a very minor typo, so we'll fix it right away.

**Comment by termoshtt** [comment]
Fixed in #119
